# Generated by Django 4.2.14 on 2026-05-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
    ]
