# Generated by Django 4.2.14 on 2026-05-22 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_aboutsection_image_alter_heroslide_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('price_prefix', models.CharField(blank=True, default='Rs', max_length=40)),
                ('price_value', models.CharField(max_length=80)),
                ('detail_1', models.CharField(blank=True, max_length=200)),
                ('detail_2', models.CharField(blank=True, max_length=200)),
                ('detail_3', models.CharField(blank=True, max_length=200)),
                ('theme', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='bronze', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_cards', to='gallery.portfoliocategory')),
            ],
            options={
                'ordering': ['category__order', 'order', 'id'],
            },
        ),
    ]
