# Generated by Django 4.2.14 on 2026-06-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_portfolioimage_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioimage',
            name='shoot_phase',
            field=models.CharField(blank=True, choices=[('pre_wedding', 'Bridal Portraits'), ('wedding_day', 'Wedding Portraits'), ('post_wedding', 'Post-Wedding Shoot'), ('before_the_blessing', 'Mehendi Moments'), ('the_celebration', 'The Celebration'), ('after_glow_portraits', 'After Glow Portraits')], default='', max_length=20),
        ),
    ]
